"project_id": "621766"
"api_token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiJ3UUVxdmhVM3ZMT2EyWGljbVV5VCIsImp0aSI6ImIzOWY2MTIxMjI1ZjViMTEwZGMxNDFmMDlkYmVmZmMwNGI1NWEwOWFmMTIwMTY4Y2ZhZTllODllZTg2YTE5N2E1YmQyYzY3ODhmMWZiZjNkIiwiaWF0IjoxNjk3NzE4NDEwLjg2Mjg1NiwibmJmIjoxNjk3NzE4NDEwLjg2Mjg1OCwiZXhwIjoxNzI5MjU0NDEwLjc5MTY1OCwic3ViIjoiMTYwNTY2MTYiLCJzY29wZXMiOlsicHJvamVjdCJdLCJkb21haW4iOm51bGwsImFzc29jaWF0aW9ucyI6WyIqIl0sInNlc3Npb24iOjB9.N2vvDU7VkgqBa6omBeqf2bM0khXBhHk33RD9pm85eUM4xdwZ00COYT-hXKWASc1xR2Xyh4BmEMoY2R8BYxIdd8cAFT5rl1O0BHcoXnVhBRLh7gmvQEqU3eAUfkRqFHBMMnLrelOcf1Bu8Ol7A6yPr-r-EcMvjILr7Jrv4PLqXOtXSRergExdUCN2LnYSlXuv-MgjUUtqyQ-PBbO7_3JVFKmcAWUZN61OBsFLsbOZZ3bjeHXUMxpZbjrRtUR9MLmzAeP_L_Zy_v2ZP1CKo7y66NCLBECIYe38hJJVkHQh8rMlvOJeRivpgXVkfSFjc00XRFhGG3excQeqXVdr2a3xHs4nnwvcTfULMpW_lgEYj9_W157bK1D6Pr7lDUM6vx4lHk0vclvU3UFz2gBHy4TspjbdfE6MRXqsu8vei2HJLNldiZgR0kzuCOMTJOwKJX3iORxtKiYzy7mXLKj3LNDbR8-SF5rKFVawGIU57Wrmo-oJ8j4hc2jtF5277DkP1FdXIBPggM-n6Hyg5AWcppcvB_TKfOavB_3Gb3x6UbymxEa_xCjvhs2IR0vqlx08IW8gnXICgYMU_tb_nDoRhJ2LIGep3G8N6D6JhJ98-pjX6x0KsUGSosBEVwXLXdOA21M-XnAte7sD-xU5TCXk3F-Lnjef1w2ZA2edEfK9PJIYHdo"
"base_path": "."
"base_url": "https://api.crowdin.com"
"preserve_hierarchy": true

files: [
  {
    "source": "/src/main/resources/*/i18n_en.*",
    "translation": "/%original_path%/i18n_%two_letters_code%.%file_extension%"
  }
]
